name: SonarQube Analysis
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-22.04  # Явно указываем версию
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential curl

      - name: Add KasperskyOS repo
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.kaspersky.com/devices/KasperskyOS/kos-deb.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/kaspersky.gpg
          echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/kaspersky.gpg] https://download.kaspersky.com/devices/KasperskyOS/1.3.0.166/ubuntu/22.04 stable main" | sudo tee /etc/apt/sources.list.d/kos.list
          sudo apt-get update

      - name: Install KasperskyOS
        run: |
          sudo apt-get install -y kos-community-edition
          echo "KOS_SDK=/opt/kasperskyos-community-edition-1.3.0.166" >> $GITHUB_ENV

      - name: Build with KOS
        run: |
          mkdir -p kos/build
          cd kos/build
          cmake -DCMAKE_TOOLCHAIN_FILE="$KOS_SDK/toolchain/share/toolchain-aarch64-kos.cmake" ..
          cmake --build .

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
