jobs:
  sonarqube:
    steps:
      - uses: actions/checkout@v4

      # Установка Bear
      - name: Install Bear
        run: sudo apt-get install -y bear

      # Генерация compile_commands.json
      - name: Generate Compilation DB
        run: |
          cd kos
          bear -- make  # Замените 'make' на вашу команду сборки

      # Анализ SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_CXX_COMPILE_COMMANDS: kos/compile_commands.json
