name: SonarQube Analysis
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            build-essential \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            binutils-aarch64-linux-gnu \
            make

      - name: Install latest CMake
        run: |
          sudo apt-get remove -y cmake
          sudo snap install cmake --classic
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Download and Install KOS SDK
        run: |
          curl -fsSL -o kos-sdk.deb "https://github.com/olegenkaorg/olegenkacyber/releases/download/v1.0/KasperskyOS-Community-Edition-RaspberryPi4b-1.3.0.166_ru.deb"
          sudo dpkg -i kos-sdk.deb || sudo apt-get install -f -y
          echo "KOS_SDK=/opt/kasperskyos-community-edition-1.3.0.166" >> $GITHUB_ENV

      - name: Verify SDK installation
        run: |
          find "$KOS_SDK" -name "toolchain-aarch64-kos.cmake"
          test -f "$KOS_SDK/toolchain/share/toolchain-aarch64-kos.cmake" || exit 1

      - name: Build project
        run: |
          mkdir -p kos/build
          cd kos/build
          cmake -DCMAKE_TOOLCHAIN_FILE="$KOS_SDK/toolchain/share/toolchain-aarch64-kos.cmake" ..
          cmake --build .
