name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Получение кода
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Шаг 2: Проверка структуры проекта
      - name: Verify Source Code
        run: |
          ls -la
          find src -name '*.cpp' -o -name '*.h'

      # Шаг 3: Анализ SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_BASE_DIR: ${{ github.workspace }}/src  # Путь к исходникам
