name: SonarCloud Analysis
on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ключевое исправление!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sqp_cf3847d0dcfd597605e7ae0adf9c72ac895346b1
            -Dsonar.organization=drone
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
